
version: "2"

linters:
  default: all

  disable:
    - wsl
    - revive
    - ireturn

  settings:
    forbidigo:
        forbid:
          - pattern: ^errors\.WithStack$
            msg: "WithStackはinfrastructure層でのみ使用してください。"
        analyze-types: true

    exhaustruct:
      exclude:
        - 'gorm\.io/gorm.Config'
        - 'gorm\.io/gorm/clause\..*'
        - 'github\.com/golang-jwt/jwt/v5\.RegisteredClaims'
        - 'log/slog\.HandlerOptions'
      allow-empty: true

    wrapcheck:
      report-internal-errors: false
      ignore-package-globs:
        - palbum/*

    depguard:
      rules:
        architecture-boundaries:
          files:
            - "internal/application/usecase/**/**/*.go"
            - "internal/domain/**/*.go"
            - "internal/infrastructure/**/*.go"
          deny:
            - pkg: "log/slog"
              desc: "Domain/UseCase層で直接ログを出力しないでください。Loggerインターフェース経由で行ってください。"

  exclusions:
    rules:
      - path: internal/infrastructure/
        linters:
          - forbidigo
      - path: internal/dependencies/
        linters:
          - forbidigo