name: test

on:
  pull_request:
    branches:
      - develop
    paths:
      - 'backend/**'

defaults:
  run:
    working-directory: backend

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-go@v6
        with:
          go-version-file: 'backend/go.mod'

      - name: Install dependencies
        run: go mod tidy

      - name: Run test
        run: go test ./...